name: 'Test'
on:
  push:
  release:
    branches: [dev,main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Install Node'
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        package-manager: yarn
    - name: 'Install Deps'
      run: npm install
    - name: 'Test'
      run: npm run test:coverage
    - name: 'Report Coverage'
      if: always() # Also generate the report if tests are failing
      uses:  davelosert/vitest-coverage-report-action@v1